services:
  lojavirtualsite:
    image: ${DOCKER_REGISTRY-}lojavirtualsite
    container_name: lojavirtualsite
    restart: unless-stopped
    build:
      context: .
      dockerfile: Web/LojaVirtual.Site/Dockerfile
    user: root
    volumes:
      - lojavirtualsite:/app/wwwroot/img/produtos
    depends_on:
      - lojavirtualcatalogo
      - lojavirtualclientes
      - lojavirtualcolaboradores
      - lojavirtualpagamentos
      - lojavirtualpedidos
      - lojavirtualredis

  lojavirtualcatalogo:
    image: ${DOCKER_REGISTRY-}lojavirtualcatalogo
    container_name: lojavirtualcatalogo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Catalogo/Dockerfile
    depends_on:
      - lojavirtualsqlserver
      - lojavirtualrabbitmq

  lojavirtualclientes:
    image: ${DOCKER_REGISTRY-}lojavirtualclientes
    container_name: lojavirtualclientes
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Clientes/Dockerfile
    depends_on:
      - lojavirtualsqlserver

  lojavirtualcolaboradores:
    image: ${DOCKER_REGISTRY-}lojavirtualcolaboradores
    container_name: lojavirtualcolaboradores
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Colaboradores/Dockerfile
    depends_on:
      - lojavirtualsqlserver

  lojavirtualpagamentos:
    image: ${DOCKER_REGISTRY-}lojavirtualpagamentos
    container_name: lojavirtualpagamentos
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Pagamentos/Dockerfile
    depends_on:
      - lojavirtualrabbitmq

  lojavirtualpedidos:
    image: ${DOCKER_REGISTRY-}lojavirtualpedidos
    container_name: lojavirtualpedidos
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Pedidos/Dockerfile
    depends_on:
      - lojavirtualsqlserver
      - lojavirtualrabbitmq

  lojavirtualnginx:
    container_name: lojavirtualnginx
    restart: unless-stopped
    depends_on:
      - lojavirtualsite
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Tools/Nginx/Dockerfile

  lojavirtualrabbitmq:
    container_name: lojavirtualrabbitmq
    restart: unless-stopped
    build:
      context: .
      dockerfile: Tools/RabbitMQ/Dockerfile
    volumes:
      - lojavirtualrabbitmq:/var/lib/rabbitmq

  lojavirtualredis:
    container_name: lojavirtualredis
    restart: unless-stopped
    build:
      context: .
      dockerfile: Tools/Redis/Dockerfile
    volumes:
      - lojavirtualredis:/data

  lojavirtualsqlserver:
    container_name: lojavirtualsqlserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: Tools/SqlServer/Dockerfile
    volumes:
      - lojavirtualsqlserver:/var/opt/mssql

volumes:
  lojavirtualsite:
  lojavirtualrabbitmq:
  lojavirtualredis:
  lojavirtualsqlserver:
  