version: '3.4'

services:
  lojavirtual.site:
    image: ${DOCKER_REGISTRY-}lojavirtualsite
    container_name: lojavirtual.site
    restart: unless-stopped
    build:
      context: .
      dockerfile: LojaVirtual.Site/Dockerfile
    depends_on:
      - lojavirtual.catalogo
      - lojavirtual.clientes
      - lojavirtual.colaboradores
      - lojavirtual.pagamentos
      - lojavirtual.pedidos
      - lojavirtual.redis

  lojavirtual.catalogo:
    image: ${DOCKER_REGISTRY-}lojavirtualcatalogo
    container_name: lojavirtual.catalogo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Catalogo/Dockerfile
    depends_on:
      - lojavirtual.sqlserver
      - lojavirtual.rabbitmq

  lojavirtual.clientes:
    image: ${DOCKER_REGISTRY-}lojavirtualclientes
    container_name: lojavirtual.clientes
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Clientes/Dockerfile
    depends_on:
      - lojavirtual.sqlserver

  lojavirtual.colaboradores:
    image: ${DOCKER_REGISTRY-}lojavirtualcolaboradores
    container_name: lojavirtual.colaboradores
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Colaboradores/Dockerfile
    depends_on:
      - lojavirtual.sqlserver

  lojavirtual.pagamentos:
    image: ${DOCKER_REGISTRY-}lojavirtualpagamentos
    container_name: lojavirtual.pagamentos
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Pagamentos/Dockerfile
    depends_on:
      - lojavirtual.rabbitmq

  lojavirtual.pedidos:
    image: ${DOCKER_REGISTRY-}lojavirtualpedidos
    container_name: lojavirtual.pedidos
    restart: unless-stopped
    build:
      context: .
      dockerfile: Services/LojaVirtual.Pedidos/Dockerfile
    depends_on:
      - lojavirtual.sqlserver
      - lojavirtual.rabbitmq
      
  lojavirtual.rabbitmq:
    container_name: lojavirtual.rabbitmq
    restart: unless-stopped
    build:
      context: .
      dockerfile: Tools/RabbitMQ/Dockerfile

  lojavirtual.redis:
    container_name: lojavirtual.redis
    restart: unless-stopped
    build:
      context: .
      dockerfile: Tools/Redis/Dockerfile

  lojavirtual.sqlserver:
    container_name: lojavirtual.sqlserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: Tools/SqlServer/Dockerfile
